version: '2'
services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    volumes:
      - "..:/jepsen"
      - "./static:/static:ro"
    ports:
      - 8080:8080
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
  node:
    container_name: jepsen-node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
    links:
      - "mysql:mysql"
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
    links:
      - "mysql:mysql"
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
    links:
      - "mysql:mysql"
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
    links:
      - "mysql:mysql"
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
    links:
      - "mysql:mysql"
